[book]
title = "Software Engineering" 
authors = ["JYU"]
language = "en" 
src = "src"

[preprocessor.gettext]
after = ["links"]

[output.html]
theme = "theme"
additional-js = ["theme/lang_switcher.js"]
additional-css = ["theme/lang_switcher.css"]
no-section-label = true
sidebar-header-nav = false

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = true

limit-results = 20
# Splits the content of a chapter into multiple search results based on the heading level.
heading-split-level = 2
copy-js = true